# Generated by Django 5.2.8 on 2025-11-30 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('zh', 'Chinese'), ('ar', 'Arabic'), ('ru', 'Russian'), ('ja', 'Japanese'), ('ko', 'Korean')], default='en', help_text='Language of the book (ISO 639-1 code)', max_length=2),
        ),
    ]
